steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        for i in 1 2 3; do
          echo "Deploying backend (attempt $i)…"
          if gcloud app deploy fastapi-api/app.yaml \
              --project=traxy-backend \
              --quiet; then
            echo "Backend deployed!"
            break
          else
            echo "!!!  >>>>>  Internal error—retrying in 10s …"
            sleep 10
          fi
        done