steps:
  # 1) Build Tailwind CSS
  - name: node:18
    dir: flask-ui
    entrypoint: bash
    args:
      - -c
      - |
        npm install
        npm run build:css
        rm -rf node_modules/


  # 2) Deploy frontend
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        # Set project
        gcloud config set project traxy-frontend
        gcloud config set gcloudignore/enabled true
        # Create .gcloudignore on the fly
        echo -e 'node_modules/\nnpm-debug.log*\n.env*\n*.log' > flask-ui/.gcloudignore
        # fetch the secret into FLASK_SECRET_KEY
        FLASK_SECRET_KEY=$(gcloud secrets versions access latest \
          --secret=FRONTEND_SECRET_KEY --project=traxy-backend)
        # substitute into the template
        sed -e "s|__FLASK_SECRET_KEY__|$$FLASK_SECRET_KEY|g" \
            flask-ui/app.yaml.template > flask-ui/app.yaml
        # deploy
        for i in 1 2 3; do
          echo "Deploying frontend (attempt $i)…"
          if gcloud app deploy flask-ui/app.yaml \
              --project=traxy-frontend \
              --quiet; then
            echo "Frontend deployed!"
            break
          else
            echo "!!! Internal error—retrying in 10s…"
            sleep 10
          fi
        done

  # 3) Deploy backend
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        # Set project
        gcloud config set project traxy-backend
        gcloud config set gcloudignore/enabled true
        # fetch each secret
        DB_USER=$(gcloud secrets versions access latest --secret=DB_USER --project=traxy-backend)
        DB_PASS=$(gcloud secrets versions access latest --secret=DB_PASS --project=traxy-backend)
        DB_NAME=$(gcloud secrets versions access latest --secret=DB_NAME --project=traxy-backend)
        CLOUD_SQL_CONNECTION_NAME=$(gcloud secrets versions access latest \
          --secret=CLOUD_SQL_CONNECTION_NAME --project=traxy-backend)
        BACKEND_SECRET_KEY=$(gcloud secrets versions access latest --secret=BACKEND_SECRET_KEY \
          --project=traxy-backend)

        # substitute into the template
        sed \
          -e "s|__DB_USER__|$$DB_USER|g" \
          -e "s|__DB_PASS__|$$DB_PASS|g" \
          -e "s|__DB_NAME__|$$DB_NAME|g" \
          -e "s|__CLOUD_SQL_CONNECTION_NAME__|$$CLOUD_SQL_CONNECTION_NAME|g" \
          -e "s|__BACKEND_SECRET_KEY__|$$BACKEND_SECRET_KEY|g" \
          fastapi-api/app.yaml.template > fastapi-api/app.yaml

        for i in 1 2 3; do
          echo "Deploying backend (attempt $i)…"
          if gcloud app deploy fastapi-api/app.yaml \
              --project=traxy-backend \
              --quiet; then
            echo "Backend deployed!"
            break
          else
            echo "!!! Internal error—retrying in 10s…"
            sleep 10
          fi
        done