steps:
  # Build Tailwind CSS
  - name: node:18
    dir: flask-ui
    entrypoint: bash
    args:
      - -c
      - |
        npm install
        npm run build:css
        rm -rf node_modules/

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        # Create .gcloudignore on the fly
        echo -e 'node_modules/\nnpm-debug.log*\n.env*\n*.log' > flask-ui/.gcloudignore
        # fetch the secret into FLASK_SECRET_KEY
        FLASK_SECRET_KEY=$(gcloud secrets versions access latest \
          --secret=FRONTEND_SECRET_KEY --project=traxy-backend)
        # substitute into the template
        sed -e "s|__FLASK_SECRET_KEY__|$$FLASK_SECRET_KEY|g" \
            flask-ui/app.yaml.template > flask-ui/app.yaml
        # deploy
        for i in 1 2 3; do
          echo "Deploying frontend (attempt $i)…"
          if gcloud app deploy flask-ui/app.yaml \
              --project=traxy-frontend \
              --quiet; then
            echo "Frontend deployed!"
            break
          else
            echo "!!! Internal error—retrying in 10s…"
            sleep 10
          fi
        done
  