service: default
runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  API_BASE_URL: 'https://traxy-backend.uc.r.appspot.com'

automatic_scaling:
  max_instances: 1

handlers:
  - url: /.*
    secure: always
    script: auto
