service: default
runtime: python39
entrypoint: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port $PORT"

env_variables:
  PROJECT_NAME: "traxy-backend"

automatic_scaling:
  max_instances: 1