"""ensure lower(username) unique

Revision ID: b6f49aae91ce
Revises: 5091363c9990
Create Date: 2025-06-11 15:55:48.766347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f49aae91ce'
down_revision: Union[str, None] = '5091363c9990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usernameLower', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_usernameLower'), 'users', ['usernameLower'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_usernameLower'), table_name='users')
    op.drop_column('users', 'usernameLower')
    # ### end Alembic commands ###
