"""Add position column to trackers

Revision ID: dd4ac1c6a051
Revises: 20250528_initial
Create Date: 2025-06-07 13:55:00.652709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4ac1c6a051'
down_revision: Union[str, None] = '20250528_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'tracker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.add_column('trackers', sa.Column('position', sa.Integer(), nullable=True, server_default=sa.text('0')))
    op.execute(
        "UPDATE trackers SET position = id WHERE position IS NULL"
    )
    op.alter_column('trackers','position',
                nullable=False,
                server_default=None
    )
    op.alter_column('trackers', 'user_id',
                existing_type=sa.INTEGER(),
                nullable=False)
    op.alter_column('trackers', 'name',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.alter_column('trackers', 'visibility',
                existing_type=sa.VARCHAR(),
                nullable=False)
    op.create_index(op.f('ix_trackers_id'), 'trackers', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_trackers_id'), table_name='trackers')
    op.alter_column('trackers', 'visibility',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trackers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trackers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('trackers', 'position')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.alter_column('activities', 'tracker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
