"""Add widget type to counters

Revision ID: f07c48eb7784
Revises: dd4ac1c6a051
Create Date: 2025-06-07 14:47:53.087010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07c48eb7784'
down_revision: Union[str, None] = 'dd4ac1c6a051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackers', sa.Column('widget_type', sa.String(length=16), nullable=False, server_default='counter'))
    op.create_check_constraint(
        'ck_trackers_widget_type',
        'trackers',
        "widget_type IN ('boolean','counter','input')"
    )
    op.alter_column('trackers', 'widget_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_trackers_widget_type', 'trackers', type_='check')
    op.drop_column('trackers', 'widget_type')
    # ### end Alembic commands ###
